Insurance-backend-main/backend/Client/Controllers/AdminController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Client.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;

namespace Client.Controllers
{
    public class AdminController : Controller
    {
        private readonly string url = "http://localhost:40316/api/";
        HttpClient client = new HttpClient();
        private readonly INotyfService _notify;

        public AdminController(INotyfService notify)
        {
            _notify = notify;
        }

        public ActionResult Dashboard()
        {
            //var list = JsonConvert.DeserializeObject(client.GetStringAsync(url + "Security/").Result);
            //ViewData["list"] = list;
            return View();
        }

        //Employee
        public IActionResult EmpList(string searchname)
        {
            var name = HttpContext.Session.GetString("SSLogin");
            if (name == null)
            {
                return RedirectToAction("Login","Login");
            }
            var emp = JsonConvert.DeserializeObject<IEnumerable<Employee>>(client.GetStringAsync(url + "Employees?searchname=" + searchname).Result);
            return View(emp);
        }

        //emp details
        public ActionResult ViewEmp(int id)
        {
            var emp = JsonConvert.DeserializeObject<Employee>(client.GetStringAsync(url + "Employees/" + id).Result);
            return View(emp);
        }
        //end emp details

        public ActionResult AddEmp()
        {
            var name = HttpContext.Session.GetString("SSLogin");
            if (name == null)
            {
                return RedirectToAction("Login", "Login");
            }
            var cn = JsonConvert.DeserializeObject<IEnumerable<CompanyDetail>>(client.GetStringAsync(url + "CompanyDetails/").Result);
            ViewData["company"] = cn;
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddEmp(Employee emp, IFormFile file)
        {
            try
            {
                if(file != null)
                {
                    string filename = Path.GetFileName(file.FileName);
                    string file_path = Path.Combine(Directory.GetCurrentDirectory(), @"wwwroot/imageEmp", filename);
                    using (var stream = new FileStream(file_path, FileMode.Create))
                    {
                        await file.CopyToAsync(stream);
                    }
                    emp.Image = "imageEmp/" + filename;
                }
                var model = client.PostAsJsonAsync<Employee>(url + "Employees/", emp).Result;
                if (model.IsSuccessStatusCode)
                {
                    _notify.Success("Create Employee Success", 5);
                }
                else
                {
                    _notify.Error("Create Failed", 5);
                }
            }
            catch (Exception)
            {
                return BadRequest();
            }
            return RedirectToAction("EmpList");
        }
        public ActionResult DelEmp(int id)
        {
            var model = client.DeleteAsync(url + "Employees/" + id).Result;
            if (model.IsSuccessStatusCode)
            {
                _notify.Success("Delete Employee Success", 5);
            }
            return RedirectToAction("EmpList");
        }

        //Feedback
        public IActionResult FeedBackList()
        {
            var name = HttpContext.Session.GetString("SSLogin");
            if (name == null)
            {
                return RedirectToAction("Login", "Login");
            }
            var fb = JsonConvert.DeserializeObject<IEnumerable<Feedback>>(client.GetStringAsync(url + "Feedbacks/").Result);
            return View(fb); 
        }
        public ActionResult DelFeedBack(int id)
        {
            var model = client.DeleteAsync(url + "Feedbacks/" + id).Result;
            if (model.IsSuccessStatusCode)
            {
                _notify.Success("Delete Feedback Success", 5);
            }
            return RedirectToAction("FeedBackList");
        }
        //HospitalInfo
        public IActionResult HospitalInfoesList(string searchname)
        {
            var name = HttpContext.Session.GetString("SSLogin");
            if (name == null)
            {
                return RedirectToAction("Login", "Login");
            }
            var hp = JsonConvert.DeserializeObject<IEnumerable<HospitalInfo>>(client.GetStringAsync(url + "HospitalInfoes?searchname=" + searchname).Result);
            return View(hp);
        }
        public IActionResult AddHp()
        {
            var name = HttpContext.Session.GetString("SSLogin");
            if (name == null)
            {
                return RedirectToAction("Login", "Login");
            }
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddHp(HospitalInfo hp)
        {
            try
            {
                var model = client.PostAsJsonAsync<HospitalInfo>(url + "HospitalInfoes/", hp).Result;
                if (model.IsSuccessStatusCode) 
                {
                    _notify.Success("Create Hospital Success", 5);
                }
                else
                {
                    _notify.Error("Create Hospital Failed", 5);
                }
            }
            catch (Exception)
            {
                return BadRequest();
            }
            return RedirectToAction("HospitalInfoesList");
        }


        public ActionResult HpDetail(int? id)
        {
            var hp = JsonConvert.DeserializeObject<HospitalInfo>(client.GetStringAsync(url + "HospitalInfoes/" + id).Result);
            return View(hp);
        }


        public ActionResult EditHp(int? id)
        {
            var name = HttpContext.Session.GetString("SSLogin");
            if (name == null)
            {
                return RedirectToAction("Login", "Login");
            }
            var hp = JsonConvert.DeserializeObject<HospitalInfo>(client.GetStringAsync(url + "HospitalInfoes/" + id).Result);
            return View(hp);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditHp(int id, HospitalInfo hp)
        {
            try
            {
                var model = client.PutAsJsonAsync<HospitalInfo>(url + "HospitalInfoes/" + id, hp).Result;
                if (model.IsSuccessStatusCode)
                {
                    _notify.Success("Update Hospital Success", 5);
                    return RedirectToAction("HospitalInfoesList");
                }
            }
            catch
            {
                return BadRequest();
            }
            return View(); 
        }
        public ActionResult DelHp(int? id)
        {
            var model = client.DeleteAsync(url + "HospitalInfoes/" + id).Result;
            if (model.IsSuccessStatusCode)
            {
                _notify.Success("Delete Hospital Success");
            }
            return RedirectToAction("HospitalInfoesList");
        }
        //Company
        public IActionResult Company(string searchname)
        {
            var name = HttpContext.Session.GetString("SSLogin");
            if (name == null)
            {
                return RedirectToAction("Login", "Login");
            }
            var cn = JsonConvert.DeserializeObject<IEnumerable<CompanyDetail>>(client.GetStringAsync(url + "CompanyDetails?searchname=" + searchname).Result);
            return View(cn);
        }
        public IActionResult AddCompany()
        {
            var name = HttpContext.Session.GetString("SSLogin");
            if (name == null)
            {
                return RedirectToAction("Login", "Login");
            }
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddCompany(CompanyDetail cn)
        {
            try
            {
                var model = client.PostAsJsonAsync<CompanyDetail>(url + "CompanyDetails/", cn).Result;
                if (model.IsSuccessStatusCode)
                {
                    _notify.Success("Create Company Success", 5);
                }
                else
                {
                    _notify.Error("Create Company Failed", 5);
                }
            }
            catch (Exception)
            {
                return BadRequest();
            }
            return RedirectToAction("Company");
        }
        public ActionResult EditCompany(int? id)
        {
            var name = HttpContext.Session.GetString("SSLogin");
            if (name == null)
            {
                return RedirectToAction("Login", "Login");
            }
            var cn = JsonConvert.DeserializeObject<CompanyDetail>(client.GetStringAsync(url + "CompanyDetails/" + id).Result);
            return View(cn);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditCompany(int id, CompanyDetail cn)
        {
            try
            {
                var model = client.PutAsJsonAsync<CompanyDetail>(url + "CompanyDetails/" + id, cn).Result;
                if (model.IsSuccessStatusCode)
                {
                    return RedirectToAction("Company");
                }
            }
            catch
            {
                return BadRequest();
            }
            return View();
        }
        public ActionResult DelCompany(int id)
        {
            var model = client.DeleteAsync(url + "CompanyDetails/" + id).Result;
            if (model.IsSuccessStatusCode)
            {
                _notify.Success("Delete Company Success", 5);
            }

Insurance-backend-main/backend/Client/Controllers/ManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;
using AspNetCoreHero.ToastNotification.Abstractions;
using Client.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace Client.Controllers
{
    public class ManagerController : Controller
    {
        private readonly string url = "http://localhost:40316/api/";
        HttpClient client = new HttpClient();
        private readonly INotyfService _notify;

        public ManagerController(INotyfService notify)
        {
            _notify = notify;
        }


        //Policy
        public IActionResult Policy(string searchname)
        {
            var name = HttpContext.Session.GetString("SSLogin");
            if (name == null)
            {
                return RedirectToAction("Login", "Login");
            }
            var policy = JsonConvert.DeserializeObject<List<ProfileResult>>(client.GetStringAsync(url + "Policies?searchname=" + searchname).Result);
            ViewData["policy"] = policy;
            return View();
        }
        public ActionResult AddPolicy()
        {
            var name = HttpContext.Session.GetString("SSLogin");
            if (name == null)
            {
                return RedirectToAction("Login", "Login");
            }
            var cn = JsonConvert.DeserializeObject<IEnumerable<CompanyDetail>>(client.GetStringAsync(url + "CompanyDetails/").Result);
            return View(cn);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddPolicy(Policy policy)
        {
            try
            {
                var model = client.PostAsJsonAsync<Policy>(url + "Policies/", policy).Result;
                if (model.IsSuccessStatusCode)
                {
                    _notify.Success("Create Policy Success", 5);
                }
                else
                {
                    _notify.Error("Create policy Failed", 5);
                }
            }
            catch (Exception)
            {
                return BadRequest();
            }
            return RedirectToAction("Policy");
        }

        
        public ActionResult DetailPolicy(int? id)
        {
            var plc = JsonConvert.DeserializeObject<Policy>(client.GetStringAsync(url + "Policies/" + id).Result);
            return View(plc);
        }

        public ActionResult EditPolicy(int? id)
        {
            var name = HttpContext.Session.GetString("SSLogin");
            if (name == null)
            {
                return RedirectToAction("Login", "Login");
            }
            var cn = JsonConvert.DeserializeObject<Policy>(client.GetStringAsync(url + "Policies/" + id).Result);
            return View(cn);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditPolicy(int id, Policy cn)
        {
            try
            {
                var model = client.PutAsJsonAsync<Policy>(url + "Policies/" + id, cn).Result;
                if (model.IsSuccessStatusCode)
                {
                    _notify.Success("Update Policy Success", 5);
                    return RedirectToAction("Policy");
                }
            }
            catch
            {
                return BadRequest();
            }
            return View();
        }
        public ActionResult DelPolicy(int id)
        {
            var model = client.DeleteAsync(url + "Policies/" + id).Result;
            if (model.IsSuccessStatusCode)
            {
                _notify.Success("Delete Policy Success", 5);
            }
            return RedirectToAction("Policy");
        }

        // Request 
        public ActionResult Request()
        {
            var name = HttpContext.Session.GetString("SSLogin");
            if (name == null)
            {
                return RedirectToAction("Login", "Login");
            }
            var request = JsonConvert.DeserializeObject<List<ProfileResult>>(client.GetStringAsync(url + "RequestDetails/").Result);
            ViewData["request"] = request;
            return View();
        }
        public ActionResult updateStatus(RequestDetail rq)
        {
            var rqId = rq.Id;
            try
            {
                var model = client.PutAsJsonAsync<RequestDetail>(url + "RequestDetails/" + rqId,rq).Result;
                if (model.IsSuccessStatusCode)
                {
                    _notify.Success("Update Request Success", 5);
                    return RedirectToAction("Request");
                }
            }
            catch
            {
                return BadRequest();
            }
            return View();
        }

        public ActionResult DelRequest(int id)
        {
            var model = client.DeleteAsync(url + "RequestDetails/" + id).Result;
            if (model.IsSuccessStatusCode)
            {
                _notify.Error("Delete Request Success", 5);
            }
            return RedirectToAction("Request");
        }

    }
}

Insurance-backend-main/backend/Client/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Insurance</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/style.css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <link rel="stylesheet" href="~/ADplugins//fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="~/ADplugins//overlayScrollbars/css/OverlayScrollbars.min.css">
    <link rel="stylesheet" href="~/ADdist/css/adminlte.min.css">
</head>
<body>
    @RenderBody()
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/ADplugins//jquery/jquery.min.js"></script>
    <script src="~/ADplugins//bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/ADplugins//overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <script src="~/ADdist/js/adminlte.js"></script>
    <script src="~/ADplugins//jquery-mousewheel/jquery.mousewheel.js"></script>
    <script src="~/ADplugins//raphael/raphael.min.js"></script>
    <script src="~/ADplugins//jquery-mapael/jquery.mapael.min.js"></script>
    <script src="~/ADplugins//jquery-mapael/maps/usa_states.min.js"></script>
    <script src="~/ADplugins//chart.js/Chart.min.js"></script>
    <script src="~/ADdist/js/demo.js"></script>
    <script src="~/ADdist/js/pages/dashboard2.js"></script>

    <!--____Notify____-->
    @await Component.InvokeAsync("Notyf")
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Insurance-backend-main/backend/Client/Views/Shared/_NavbarAdmin.cshtml
@using Microsoft.AspNetCore.Http;
<div class="preloader flex-column justify-content-center align-items-center">
    <img class="animation__wobble" src="~/ADdist/img/Health-Insurance-logo.png" alt="Health Insurance" height="200" width="200">
</div>
<nav class="main-header navbar navbar-expand navbar-dark" style="background-color:#ffffff; border-bottom:0px">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars" style="color:#333"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/Home/HomePages" class="nav-link" style="color:#333">Home</a>
        </li>
    </ul>

    <ul class="navbar-nav ml-auto">
        <li class="nav-item">
            <a href="/Login/Logout" class="d-block">Logout</a>
        </li>
    </ul>


</nav>
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <a @*href="../Views/Home/HomePages.cshtml"*@ class="brand-link">
        <img src="~/ADdist/img/Health-Insurance-logo.png" alt="Health Insurance Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light" style="color:white;"><strong>Health Insurance</strong></span>
    </a>
    <partial name="../Shared/_Sidebar.cshtml" />
</aside>

Insurance-backend-main/backend/Client/Views/Shared/_Sidebar.cshtml
<div class="sidebar sidebar-profile">
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
            <img src="~/@Context.Session.GetString("SSImage")" class="img-circle elevation-2" alt="User Image">
        </div> 
        <div class="info">
            @using Microsoft.AspNetCore.Http;
            <p>
                <a href="/Login/Profile/@Context.Session.GetInt32("EmpId")" class="d-block">@Context.Session.GetString("Username")</a>
            </p>
        </div>
    </div>
    <!-- Sidebar Menu -->
    <div class="sidebar">
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-item menu-open">
                    <a asp-controller="Admin" asp-action="Dashboard" class="nav-link active">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>
                            Dashboard
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link">
                        <i class="nav-icon fas fa-copy"></i>
                        <p>
                            Employee
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a asp-controller="Admin" asp-action="EmpList" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>List of Employee</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Admin" asp-action="AddEmp" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Add Employee</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link">
                        <i class="far fa-hospital"></i>
                        <p>
                            HospitalInfo
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a asp-controller="Admin" asp-action="HospitalInfoesList" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>List of Hospital</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Admin" asp-action="AddHp" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Add Hospital</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link">
                        <i class="fas fa-building"></i>
                        <p>
                            Company
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a asp-controller="Admin" asp-action="Company" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>List of Company</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Admin" asp-action="AddCompany" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Add Company</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link">
                        <i class="fas fa-book"></i>
                        <p>
                            Policy
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a asp-controller="Manager" asp-action="Policy" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>List of Policy</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Manager" asp-action="AddPolicy" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Add Policy</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Admin" asp-action="FeedBackList">
                        <i class="fas fa-comment"></i>
                        <p>
                            Feedback
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Manager" asp-action="Request">        
                        <i class="far fa-envelope"></i>
                        <p>
                            Employee request
                        </p>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</div>